### ISSUE TITLE
Home page doesn't  look nice

### ISSUE THREAD

**Issue by alexvong243f** [CSCI3100-Pick-Up/pick-up#7]
![pick-up-1](https://user-images.githubusercontent.com/10696787/37567332-86ff16e4-2b00-11e8-83a3-0cff12df1233.png)

**Comment by alexvong243f** [comment]
Other pages work fine, e.g.
![pick-up-2](https://user-images.githubusercontent.com/10696787/37567369-f32e35de-2b00-11e8-92e1-ecc2e57f6708.png)

**Comment by alexvong243f** [comment]
It now looks like:
![pick-up-3](https://user-images.githubusercontent.com/10696787/37567444-fce22378-2b01-11e8-94b1-01de1e7a68f7.png)

**Comment by articulatesnail** [comment]
This screenshot shows me that the page isn't commencting with landingLogin.css, but is with the bootstrap link, which is a url, so that shouldn't run into any problems

**Comment by alexvong243f** [comment]
Fixed in latest master.
